apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: praisethelord
    application-id: app_1db83000-2c04-4a3a-9df9-295f8d3e798c
  name: praisethelord
spec:
  selector:
    app: praisethelord
