apiVersion: v1
kind: Namespace
metadata:
  name: asdasdasd-dev
  labels:
    environment-id: env_2c8308a9-7cbe-4d8f-bb7a-ab10824cc0a1
    project-id: project_bd80e2c3-4c18-4dfc-8b33-2c3ebd824c50
    project-name: axcdtgfbv
    environment-name: dev
    organization-id: org_e6d69564-e5ec-4b6c-b23c-e72de3fdc902
