apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 200
      memoryRequestMb: 100
      memoryLimitMb: 200
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: mist-main
  minReplicas: 1
  maxReplicas: 5
  terminationGracePeriodSeconds: 30
  nodeSelector:
    kubernetes.io/hostname: my-node-name
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: ross
    env: production
    version: v0.0.1
    applicationId: app_72da35da-f078-41a1-ad4c-f5bb459ef583
    projectId: project_bd80e2c3-4c18-4dfc-8b33-2c3ebd824c50
    organizationId: org_e6d69564-e5ec-4b6c-b23c-e72de3fdc902
    environmentId: env_68ddf58b-b44e-4a3e-a9f4-e395b5395afd
    environmentName: testcxzczxc
  horizontalAutoScalingRules:
    - ruleType: cpu
      percentage: 80
  volumes:
    - name: my-volume
      type: PersistentVolumeClaim
      pvc:
        claimName: my-claim
  type: service
  serviceType: LoadBalancer
  name: mist
  namespace: foo
