apiVersion: transformers.customplugin.co/v1
kind: SkyUAppTransformer
metadata:
  name: skyu-deployment
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: skyu-app-transformer
spec:
  applicationContainers:
    - imageTag: latest
      cpuRequestMili: 100
      cpuLimitMili: 200
      memoryRequestMb: 100
      memoryLimitMb: 200
      args: []
      command: []
      configMounts: []
      applicationPorts: []
      healthChecks: []
      name: mist-main
  minReplicas: 1
  maxReplicas: 5
  terminationGracePeriodSeconds: 30
  nodeSelector:
    kubernetes.io/hostname: my-node-name
  suspend: false
  ttlSecondsAfterFinished: 0
  labels:
    app: heyBoss
    env: production
    applicationId: app_47a2f0d6-b36c-401d-b70d-458040c6f5e9
    projectId: project_bd80e2c3-4c18-4dfc-8b33-2c3ebd824c50
    organizationId: org_e6d69564-e5ec-4b6c-b23c-e72de3fdc902
    environmentId: env_a0af8b4b-4aa6-41c6-89ac-1b057da80d5d
    environmentName: prod
  horizontalAutoScalingRules:
    - ruleType: cpu
      percentage: 80
  volumes:
    - name: my-volume
      type: PersistentVolumeClaim
      pvc:
        claimName: my-claim
  type: service
  serviceType: LoadBalancer
  name: mist
  namespace: asdasdasd-prod
